---
- name: Install httpd server
  dnf:
    name: httpd
    state: present
  
- name: Kubernetes port mapping configuration
  copy:
    src: files/k8s-service.conf
    dest: /etc/httpd/conf.d/k8s-service.conf
    owner: root
    group: root
    mode: "0644"

- name: Start httpd service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Copy join token to node
  copy:
    src: /home/ansible/kube-output.txt
    dest: /tmp/kube-output.txt
    owner: root
    group: root
    mode: "0777"

- name: Extract worker token
  shell: tail -n2 /tmp/kube-output.txt > /tmp/join-worker-command.sh

- name: Add kubernetes node into the cluster
  command: sh /tmp/join-worker-command.sh
